### ISSUE TITLE
Nothing is cached when staticFileGlobs is explicitly set.

### ISSUE THREAD

**Issue by rion18** [ragingwind/sw-precache-webpack-dev-plugin#2]
Hi, first of all, thanks for making this plugin, it really helps debugging Service Workers. I have a project that has a public folder where I put my static assets such as images an icons etc. I want these to be cached along with the files emitted by Webpack.

```javascript
new SWPrecacheWebpackDevPlugin({
  filename: 'sw.js',
  maximumFileSizeToCacheInBytes: 4194304,
  minify: false,
  staticFileGlobsIgnorePatterns: [/\.map$/], // use this to ignore sourcemap files 
  mergeStaticsConfig: true, // if you don't set this to true, you won't see any webpack-emitted assets in your serviceworker config 
  staticFileGlobs: [
    'public/media/**.*',
    'public/*.html',
  ],
  stripPrefix: 'public'
})
```

In this case, I would expect to find the objects emitted by Webpack along with my *public* files, however, nothing is cached:

![image](https://cloud.githubusercontent.com/assets/5338637/23535632/8e95b560-ff8d-11e6-9a93-952034045df9.png)

If I remove *staticFileGlobs*, then it caches the objects emitted by Webpack but NOT my *public* files.

```javascript
new SWPrecacheWebpackDevPlugin({
  filename: 'sw.js',
  maximumFileSizeToCacheInBytes: 4194304,
  minify: false,
  staticFileGlobsIgnorePatterns: [/\.map$/], // use this to ignore sourcemap files 
  mergeStaticsConfig: true // if you don't set this to true, you won't see any webpack-emitted assets in your serviceworker config 
})
```

![image](https://cloud.githubusercontent.com/assets/5338637/23535648/b034341c-ff8d-11e6-8f65-5af8b5a60d8d.png)

So far, the only way I've found to cache my files is to set a *runtimeCaching* parameter, which feels a bit hacky:

```javascript
new SWPrecacheWebpackDevPlugin({
  filename: 'sw.js',
  maximumFileSizeToCacheInBytes: 4194304,
  minify: false,
  staticFileGlobsIgnorePatterns: [/\.map$/], // use this to ignore sourcemap files 
  mergeStaticsConfig: true, // if you don't set this to true, you won't see any webpack-emitted assets in your serviceworker config 
  runtimeCaching: [{
        urlPattern: /^http:\/\/localhost/,
        handler: 'cacheFirst'
      }]
})
```

![image](https://cloud.githubusercontent.com/assets/5338637/23535737/4ea3d102-ff8e-11e6-87df-64f79307f061.png)

This way, I can cache my files under the *toolbox-cache*. It works, but as I said, it's a hacky solution. Hope we can get this fixed, have a great day!

**Comment by ragingwind** [comment]
How you use absolute path instead of relative path. refer to https://github.com/codebusking/react-pwa-hello-world/blob/master/webpack.config.js#L84

**Comment by rion18** [comment]
Thanks for your answer. I did try that.

I actually tried with EVERY combination you can think of, of the following params:

```javascript
  mergeStaticsConfig: true, // if you don't set this to true, you won't see any webpack-emitted assets in your serviceworker config 
  stripPrefixMulti: {
    [path.resolve(appDirectory, './build')]: './build',
    [path.resolve(appDirectory, './public')]: './public',
  },
  staticFileGlobs: [
    path.join(path.resolve(appDirectory, './build'), '**/*'),
    path.join(path.resolve(appDirectory, './public'), '**/*'),
    path.join(path.resolve(appDirectory, './public/media'), '**/*'),
    path.join(path.resolve(appDirectory, './media'), '**/*'),
    path.join(path.resolve(appDirectory, './build/media'), '**/*')
  ],
```

No matter what I do, my *sw.js* file starts with this:
```javascript
// Manipulated by SWPrecacheWebpackDevPlugin Mon Mar 06 2017 12:51:36 GMT-0500 (SA Pacific Standard Time)
var precacheConfig = [
    ['static/js/bundle.js', 'abbf4d8af6df2cbc1cb986bd26a97fc3'],
    ['static/js/bundle.js.map', '81b145bd06a369d6a2b74e914f8316b5'],
    ['index.html', '5390bf100354a636f9cbc6b6edb7279a']
]
```

Any ideas?

**Comment by ragingwind** [comment]
It looks your some of assets are not in webpack's assets list that means some of files are in public or media aren't dealt by webpack. In my case of, I'm using copy webpack plugin and copy all of assets into build directory. 

I will have a look for a solution for your case.

**Comment by ragingwind** [comment]
@rion18 Would you test with master branch? I pushed patch for this issue. but I'm not pretty sure about the result even I built test app. This plugin will [determine where its files are written mem-fs or not](https://github.com/ragingwind/sw-precache-webpack-dev-plugin/commit/8babdf7938609f6db5178859b88f6f3365e285c6#diff-168726dbe96b3ce427e7fedce31bb0bcR23). However, In my point of view, It's not solid rules, so you should use non-conflict path to cache.

**Comment by ragingwind** [comment]
Close it now. Feel free to reopen it

**Comment by rion18** [comment]
In the end, I couldn't make it work in that version. However, updating to 0.2.0, it worked! Thanks so much for your time!! Although... It seems the property `mergeStaticsConfig` is now ignored...

**Comment by rion18** [comment]
By the way: I forked the repo, and I found a quick and dirty solution. I don't believe this could be on this repo, since I got rid of a multimatch condition. Anyhow, here's the commit:

https://github.com/devsu/sw-precache-webpack-dev-server-plugin/commit/c9827c8595c7cb2d1b067908e0d3120d79d6a439

Again, thanks a bunch!
